-- Active: 1742763600964@@localhost@3306@agiletic_app
CREATE OR REPLACE VIEW usuarios( token, name, email, imgName, rolId, rolDes, emploNom, emploApe, emploFecNac, gerId, gerDes , activado, reinicio ,created_at , id) AS( SELECT a.token, a.name, a.email, c.emploAvatar, a.rolId, b.RolDes, c.emploNom, c.emploApe, c.emploFecNac, c.gerId, d.gerDes , a.activado , a.reinicio ,a.created_at , a.id FROM users a JOIN segu_roles b ON a.rolId = b.rolId LEFT JOIN parm_empleados c ON a.id = c.id LEFT JOIN parm_gerencia d ON c.gerId = d.gerId);
CREATE OR REPLACE VIEW tblusuarios( empId, empresa,rolId,id, name, email, rolDes, emploNom, emploApe, emploFecNac, gerId,gerDes, activado, reinicio, created_at ) AS( SELECT  a.empId , e.`empDes`, b.rolID, a.id, a.name, a.email, b.RolDes, c.emploNom, c.emploApe, c.emploFecNac, d.gerId,d.gerDes, CASE WHEN a.activado = 'A' THEN "ACTIVADO" WHEN a.activado = 'D' THEN "DESACTIVADO" END AS 'activado', CASE WHEN a.reinicio = 'S' THEN "SI" WHEN a.reinicio = 'N' THEN "NO" END 'reinicio', a.created_at  FROM users a JOIN segu_roles b ON a.rolId = b.rolId LEFT JOIN parm_empleados c ON a.id = c.id LEFT JOIN parm_gerencia d ON c.gerId = d.gerId  JOIN parm_empresa  e on e.`empId` = a.`empId`  ORDER BY a.created_at DESC);
CREATE OR REPLACE VIEW regiones (regId, regDes, regCod, empId, paiId, created_at, updated_at , paiDes , paiCod) as ( SELECT a.regId, a.regDes, a.regCod, a.empId, a.paiId, a.created_at, a.updated_at , paiDes , paiCod from parm_region a join parm_pais b on a.paiId = b.paiId );       
CREATE OR REPLACE VIEW comunas (comId, comDes, comCod, empId, paiId, regId,ciuId , ciuDes , created_at, updated_at , paiCod , paiDes , regCod , regDes) AS (SELECT comId, comDes, comCod, a.empId, a.paiId, a.regId,  a.ciuId , ciuDes , a.created_at, a.updated_at , paicod , paiDes , regCod , regDes  from parm_comuna a JOIN parm_region b on a.regId = b.regId join parm_pais c on a.paiId = c.paiId join parm_ciudad d on a.ciuId = d.ciuId);
CREATE OR REPLACE VIEW ciudades ( empId, paiId, regId, created_at, updated_at , paiCod , paiDes , regCod , regDes , ciuId , ciuDes , ciuCod) AS (SELECT a.empId, a.paiId, a.regId, a.created_at, a.updated_at , paicod , paiDes , regCod , regDes , a.ciuId , ciuDes , ciuCod from parm_ciudad a JOIN parm_region b on a.regId = b.regId JOIN parm_pais c on a.paiId = c.paiId ) ;
CREATE OR REPLACE VIEW proveedores( id,rut,nombre,nombre_fantasia,giro,pais , pais_id ,region, region_id,comuna, comuna_id,ciudad,ciudad_id, direccion,numero,telefono ,es_cliente, es_proveedor,mail , activado , place , lat , lng)AS ( SELECT prvId ,prvRut, prvNom, prvNom2, prvGiro,b.paiDes , b.`paiId` , c.regDes , c.`regId`,d.comDes, d.`comId` ,e.ciuDes , e.`ciuId`, prvDir, prvNum , prvTel, prvCli, prvPrv, prvMail , prvAct, prvPlace, prvLat, prvLong from parm_proveedor a join parm_pais b on a.paiId = b.paiId join parm_region c on a.regId = c.regId join parm_comuna d on a.comId = d.comId join parm_ciudad e on a.ciuId = e.ciuId );
CREATE OR REPLACE VIEW proveedores_dir(id,rut ,pais,region,comuna,ciudad,direccion,numero) AS ( SELECT a.prvdId , f.prvRut,b.paiDes , c.regDes,d.comDes,e.ciuDes, prvdDir, prvdNum From parm_prv_suc a join parm_pais b on a.paiId = b.paiId join parm_region c on a.regId = c.regId join parm_comuna d on a.comId = d.comId join parm_ciudad e on a.ciuId = e.ciuId join parm_proveedor f on a.prvId = f.prvID);
CREATE OR REPLACE VIEW productos( id, cod_pareo, descripcion, observaciones, cod_rapido, cod_barra, tipo,grupo , sub_grupo , color , moneda ,costo, neto, bruto, medida , peso, minimo, inventariable, created_at, updated_at) As ( SELECT a.prdId, prdCod, prdDes, prdObs, prdRap, prdEan, prdTip,c.grpDes , d.grpsDes , e.colDes , b.monCod , prdCost, prdNet, prdBrut, f.unDes , prdPes, prdMin,prdInv , a.created_at, a.updated_at from parm_producto a join parm_moneda b on a.monId = b.monId join parm_grupo c on a.grpId = c.grpId join parm_sub_grupo d on a.grpsId = d.grpsId join parm_color e on a.colId = e.colId join parm_un_medida f on a.unId = f.unId);
CREATE OR REPLACE VIEW ordenes_de_trabajos AS( SELECT a.idOrdt AS id, d.idOrdtd AS id_det, b.orpNumRea AS orden_produccion, b.orpidEta AS cod_etapa, c.etaDes AS etapa, b.orpFech AS orden_prod_fec, a.orptUsrG AS usuario_genera, CASE WHEN a.orptEst = 1 THEN 'PENDIENTE' WHEN a.orptEst = 2 THEN 'EN PROCESO' WHEN a.orptEst = 3 THEN 'APROBADA' WHEN a.orptEst = 4 THEN 'RECHAZADA' END AS estado, a.orptPrio AS prioridad, d.ordtdPrdCod AS cod_producto, d.ordtdPrdDes AS producto, d.ortdSol AS solicitado, d.ortdProd AS producido, a.created_at AS created_at, a.updated_at AS updated_at FROM ( ord_trabajo a JOIN ord_produccion b ON (a.idOrp = b.idOrp) JOIN ord_trabajo_det d ON (a.idOrdt = d.idOrdt) JOIN etapasUser c ON (c.idEta = d.orpdidEta) ) );
CREATE OR REPLACE VIEW mezclas AS( SELECT a.idMez AS id, a.mezUsu AS usuario, a.mezLotSal AS lote_salida, a.mezKil AS kilos, a.mezMaq AS maquina, b.etaDes AS etapa, a.mezprdDes AS producto, CASE WHEN a.mezTip = 'S' THEN 'SACA' WHEN a.mezTip = 'B' THEN 'BINS' END AS tipo, CASE WHEN a.mezEst = 'P' THEN 'PENDIENTE' WHEN a.mezEst = 'A' THEN 'APROBADA' END AS estado_pro, CASE WHEN a.mezEstCtl = 'P' THEN 'PENDIENTE' WHEN a.mezEstCtl = 'A' THEN 'APROBADA' WHEN a.mezEstCtl = 'R' THEN 'RECHAZADA' END AS estado_control, CASE WHEN a.mezTurn = 1 THEN 'TURNO 1' WHEN a.mezTurn = 2 THEN 'TURNO2' END AS turno, a.mezObs AS observaciones, a.created_at AS created_at, a.updated_at AS updated_at FROM mezcla a JOIN etapasUser b ON (a.mezidEta = b.idEta) );
CREATE OR REPLACE VIEW extrusiones AS( SELECT a.idExt AS id, a.extUsu AS usuario, a.extLotSal AS lote_bobina, a.extAnbob AS ancho_bobina, a.extMaq AS maquina, a.extKilApr AS kilos, a.extKilR AS kilos_repro, b.etaDes AS etapa, a.extPrdDes AS producto, c.mezLotSal AS lote_mezcla, a.extFor AS formato, d.motDes AS mot_rechazo, CASE WHEN a.extEst = 'P' THEN 'PENDIENTE' WHEN a.extEst = 'A' THEN 'APROBADA' END AS estado_pro, CASE WHEN a.extEstCtl = 'P' THEN 'PENDIENTE' WHEN a.extEstCtl = 'A' THEN 'APROBADA' WHEN a.extEstCtl = 'R' THEN 'RECHAZADA' END AS estado_control, CASE WHEN a.extTurn = 1 THEN 'TURNO 1' WHEN a.extTurn = 2 THEN 'TURNO2' END AS turno, a.extObs AS observaciones, a.created_at AS created_at, a.updated_at AS updated_at FROM  extrusion a LEFT JOIN etapasUser b ON a.extidEta = b.idEta LEFT JOIN mezcla c ON  a.extIdMez = c.idMez LEFT JOIN mot_rechazo d ON  a.extIdMot = d.idMot);
CREATE OR REPLACE VIEW ordenes_de_termoformado AS( SELECT a.idOrdt AS id, d.idOrdtd as id_det, e.idTer AS id_termo, b.orpUsrG AS usuario_genera, b.orpNumOC AS oc, b.idOrp AS op, b.orpFech AS orden_prod_fec, CASE WHEN a.orptEst = 1 THEN 'PENDIENTE' WHEN a.orptEst = 2 THEN 'EN PROCESO' WHEN a.orptEst = 3 THEN 'CERRADA' END AS estado_orden, CASE WHEN e.terEst = 'P' THEN 'PENDIENTE' WHEN e.terEst = 'A' THEN 'APROBADA' WHEN e.terEst = 'R' THEN 'RECHAZADA' END AS estado_termo_op, CASE WHEN e.terEstCtl = 'P' THEN 'PENDIENTE' WHEN e.terEstCtl = 'A' THEN 'APROBADA' WHEN e.terEstCtl = 'R' THEN 'RECHAZADA' END AS estado_termo_ctl, a.orptPrio AS prioridad, d.ordtdPrdDes AS producto, d.ortdSol AS cantidad_sol, e.terLotSal AS lote_salida, CASE WHEN e.terTip = 'P' THEN 'Pallet' WHEN e.terTip = 'B' THEN 'Bins' END AS tipo, e.terMaq AS maquina, CASE WHEN e.terTurn = 1 THEN 'Turno 1' WHEN e.terTurn = 2 THEN 'Turno 2' END AS turno, f.prdDes AS tipo_caja, e.terLotCaja AS lote_caja, g.prdDes AS tipo_bolsa, e.terLotBolsa AS lote_bolsa, a.created_at AS created_at, a.updated_at AS updated_at FROM ord_trabajo a JOIN ord_produccion b ON (a.idOrp = b.idOrp) JOIN ord_trabajo_det d ON ( a.empId = d.empId AND a.idOrdt = d.idOrdt ) JOIN etapasUser c ON (d.orpdidEta = c.idEta)  JOIN termoformado e ON ( a.empId = e.empId AND a.idOrdt = e.idOrdt ) LEFT JOIN producto f ON (e.terPrdCaja = f.idPrd) LEFT JOIN producto g ON (e.terPrdBolsa = g.idPrd) WHERE c.idEta = 5 );
CREATE OR REPLACE VIEW ordenes_de_envasado AS( SELECT a.idOrdt AS id, e.idEnv AS id_envasado, b.orpUsrG AS usuario_genera, b.orpNumOC AS oc, b.idOrp AS op, b.orpFech AS orden_prod_fec, CASE WHEN a.orptEst = 1 THEN 'PENDIENTE' WHEN a.orptEst = 2 THEN 'EN PROCESO' WHEN a.orptEst = 3 THEN 'CERRADA' END AS estado_orden, CASE WHEN e.envEst = 'P' THEN 'PENDIENTE' WHEN e.envEst = 'A' THEN 'APROBADA' WHEN e.envEst = 'R' THEN 'RECHAZADA' END AS estado_termo_op, CASE WHEN e.envEstCtl = 'P' THEN 'PENDIENTE' WHEN e.envEstCtl = 'A' THEN 'APROBADA' WHEN e.envEstCtl = 'R' THEN 'RECHAZADA' END AS estado_termo_ctl, a.orptPrio AS prioridad, d.ordtdPrdDes AS producto, d.ortdSol AS cantidad_sol, e.envLotSal AS lote_salida, e.envMaq AS maquina, CASE WHEN e.envTurn = 1 THEN 'Turno 1' WHEN e.envTurn = 2 THEN 'Turno 2' END AS turno, f.prdCod AS tipo_caja, e.envLotCaja AS lote_caja, g.prdcod AS tipo_bolsa, e.envLotBolsa AS lote_bolsa, a.created_at AS created_at, a.updated_at AS updated_at FROM ord_trabajo a JOIN ord_produccion b ON (a.idOrp = b.idOrp) JOIN ord_trabajo_det d ON ( a.empId = d.empId AND a.idOrdt = d.idOrdt ) JOIN etapasUser c ON (d.orpdidEta = c.idEta) LEFT JOIN termoformado h ON ( a.empId = h.empId AND a.idOrdt = h.idOrdt ) JOIN envasado e ON ( a.empId = e.empId AND e.idTer = h.idTer ) LEFT JOIN producto f ON (e.envPrdCaja = f.idPrd) LEFT JOIN producto g ON (e.envPrdBolsa = g.idPrd) );
CREATE OR REPLACE VIEW `ordenes_de_inyeccion` AS( SELECT `a`.`idOrdt` AS `id`, d.idOrdtd as id_det, `e`.`idIny` AS `id_inye`, `b`.`orpUsrG` AS `usuario_genera`, `b`.`orpNumOc` AS `oc`, `b`.`idOrp` AS `op`, `b`.`orpFech` AS `orden_prod_fec`, CASE WHEN `a`.`orptEst` = 1 THEN 'PENDIENTE' WHEN `a`.`orptEst` = 2 THEN 'EN PROCESO' WHEN `a`.`orptEst` = 3 THEN 'CERRADA' END AS `estado_orden`, CASE WHEN `e`.`inyEst` = 'P' THEN 'PENDIENTE' WHEN `e`.`inyEst` = 'A' THEN 'APROBADA' WHEN `e`.`inyEst` = 'R' THEN 'RECHAZADA' END AS `estado_inye_op`, CASE WHEN `e`.`inyEstCtl` = 'P' THEN 'PENDIENTE' WHEN `e`.`inyEstCtl` = 'A' THEN 'APROBADA' WHEN `e`.`inyEstCtl` = 'R' THEN 'RECHAZADA' END AS `estado_inye_ctl`, `a`.`orptPrio` AS `prioridad`, `d`.`ordtdPrdDes` AS `producto`, `d`.`ortdSol` AS `cantidad_sol`, `e`.`inyLotSal` AS `lote_salida`, CASE WHEN `e`.`inyTip` = 'P' THEN 'Pallet' WHEN `e`.`inyTip` = 'B' THEN 'Bins' END AS `tipo`, `e`.`inyMaq` AS `maquina`, CASE WHEN `e`.`inyTurn` = 1 THEN 'Turno 1' WHEN `e`.`inyTurn` = 2 THEN 'Turno 2' END AS `turno`, `f`.`prdDes` AS `tipo_caja`, `e`.`inyLotCaja` AS `lote_caja`, `g`.`prdDes` AS `tipo_bolsa`, `e`.`inyLotBolsa` AS `lote_bolsa`, h.mezLotSal AS 'lote_mezcla', `a`.`created_at` AS `created_at`, `a`.`updated_at` AS `updated_at` FROM `ord_trabajo` `a` JOIN `ord_produccion` `b` ON `a`.`idOrp` = `b`.`idOrp` JOIN `ord_trabajo_det` `d` ON `a`.`empId` = `d`.`empId` AND `a`.`idOrdt` = `d`.`idOrdt` JOIN `etapasUser` `c` ON `d`.`orpdidEta` = `c`.`idEta` JOIN `inyeccion` `e` ON `a`.`empId` = `e`.`empId` AND `a`.`idOrdt` = `e`.`idOrdt` AND d.idOrdtd = e.idOrdtd LEFT JOIN `producto` `f` ON `e`.`inyPrdCaja` = `f`.`idPrd` LEFT JOIN `producto` `g` ON `e`.`inyPrdBolsa` = `g`.`idPrd` LEFT JOIN mezcla h ON e.inyIdMez = h.idMez WHERE `c`.`idEta` = 7 );
CREATE OR REPLACE VIEW `ordenes_de_impresion` AS( SELECT `a`.`idOrdt` AS `id`, d.idOrdtd as id_det,`e`.`idImp` AS `id_impre`, `b`.`orpUsrG` AS `usuario_genera`, `b`.`orpNumOc` AS `oc`, `b`.`idOrp` AS `op`, `b`.`orpFech` AS `orden_prod_fec`, CASE WHEN `a`.`orptEst` = 1 THEN 'PENDIENTE' WHEN `a`.`orptEst` = 2 THEN 'EN PROCESO' WHEN `a`.`orptEst` = 3 THEN 'CERRADA' END AS `estado_orden`, CASE WHEN `e`.`impEst` = 'P' THEN 'PENDIENTE' WHEN `e`.`impEst` = 'A' THEN 'APROBADA' WHEN `e`.`impEst` = 'R' THEN 'RECHAZADA' END AS `estado_impre_op`, CASE WHEN `e`.`impEstCtl` = 'P' THEN 'PENDIENTE' WHEN `e`.`impEstCtl` = 'A' THEN 'APROBADA' WHEN `e`.`impEstCtl` = 'R' THEN 'RECHAZADA' END AS `estado_impre_ctl`, `a`.`orptPrio` AS `prioridad`, `d`.`ordtdPrdDes` AS `producto`, `d`.`ortdSol` AS `cantidad_sol`, `e`.`impLotSal` AS `lote_salida`, CASE WHEN `e`.`impTip` = 'P' THEN 'Pallet' WHEN `e`.`impTip` = 'B' THEN 'Bins' END AS `tipo`, `e`.`impMaq` AS `maquina`, CASE WHEN `e`.`impTurn` = 1 THEN 'Turno 1' WHEN `e`.`impTurn` = 2 THEN 'Turno 2' END AS `turno`, `f`.`prdDes` AS `tipo_caja`, `e`.`impLotCaja` AS `lote_caja`, `g`.`prdDes` AS `tipo_bolsa`, `e`.`impLotBolsa` AS `lote_bolsa`, h.idTer AS 'lote_mezcla', `a`.`created_at` AS `created_at`, `a`.`updated_at` AS `updated_at` FROM `ord_trabajo` `a` JOIN `ord_produccion` `b` ON `a`.`idOrp` = `b`.`idOrp` JOIN `ord_trabajo_det` `d` ON `a`.`empId` = `d`.`empId` AND `a`.`idOrdt` = `d`.`idOrdt` JOIN `etapasUser` `c` ON `d`.`orpdidEta` = `c`.`idEta` JOIN `impresion` `e` ON `a`.`empId` = `e`.`empId` AND `a`.`idOrdt` = `e`.`idOrdt` LEFT JOIN `producto` `f` ON `e`.`impPrdCaja` = `f`.`idPrd` LEFT JOIN `producto` `g` ON `e`.`impPrdBolsa` = `g`.`idPrd` LEFT JOIN termoformado h ON e.impidTer = h.idTer WHERE `c`.`idEta` = 8 );
CREATE OR REPLACE VIEW `iny_tot_bul_prd` AS( SELECT a.idIny, a.idOrdt, a.idOrdtd, c.ordtdPrdCod, b.inydCaja, f.equiPrdBulto, SUM(b.inydCaja * f.equiPrdBulto) AS tot_prd_bul FROM inyeccion a JOIN inyeccion_det b ON b.idIny = a.idIny AND a.empId = b.empId JOIN ord_trabajo_det c ON c.idOrdt = a.idOrdt AND c.idOrdtd = a.idOrdtd JOIN producto d ON d.prdCod = c.ordtdPrdCod JOIN prd_equivalencia f ON f.idPrd = d.idPrd where a.empId =1 GROUP by a.idIny, a.idOrdt, a.idOrdtd, c.ordtdPrdCod );
CREATE OR REPLACE VIEW `imp_tot_bul_prd` AS( SELECT a.idImp, a.idOrdt, a.idOrdtd, c.ordtdPrdCod, b.impdCajaAcu, f.equiPrdBulto, SUM(b.impdCajaAcu * f.equiPrdBulto) AS tot_prd_bul FROM impresion a JOIN impresion_det b ON b.idImp = a.idImp AND a.empId = b.empId JOIN ord_trabajo_det c ON c.idOrdt = a.idOrdt AND c.idOrdtd = a.idOrdtd JOIN producto d ON d.prdCod = c.ordtdPrdCod JOIN prd_equivalencia f ON f.idPrd = d.idPrd WHERE a.empId = 1 GROUP BY a.idImp, a.idOrdt, a.idOrdtd, c.ordtdPrdCod );
CREATE OR REPLACE VIEW `ter_tot_bul_prd` AS( SELECT a.idTer, a.idOrdt, a.idOrdtd, c.ordtdPrdCod, b.terdCaja, f.equiPrdBulto, SUM(b.terdCaja * f.equiPrdBulto) AS tot_prd_bul FROM termoformado a JOIN termoformado_det b ON b.idTer = a.idTer AND a.empId = b.empId JOIN ord_trabajo_det c ON c.idOrdt = a.idOrdt AND c.idOrdtd = a.idOrdtd JOIN producto d ON d.prdCod = c.ordtdPrdCod JOIN prd_equivalencia f ON f.idPrd = d.idPrd WHERE a.empId = 1 GROUP BY a.idTer, a.idOrdt, a.idOrdtd, c.ordtdPrdCod );

CREATE OR REPLACE VIEW Aop_pendiente AS (select sum((SELECT COUNT(0) FROM ord_produccion_det e WHERE e.idOrp = a.idOrp)- (SELECT COUNT(0) FROM ord_trabajo_det  f WHERE f.ortidOrp = a.idOrp)) as pendientes , a.idOrp from ord_produccion a GROUP by idOrp);
CREATE OR REPLACE VIEW menu_roles AS ( SELECT a.empId, a.molId, e.rolId, b.molDes,b.molIcon,c.optId,c.optDes,c.optLink FROM segu_emp_mol_opt a  JOIN segu_modulo  b ON a.molId = b.molId JOIN segu_opciones c ON a.optId = c.optId  JOIN segu_emp_mol_rol e ON a.molId =e.molId and a.empId = e.empId );
CREATE OR REPLACE VIEW menu_roles_sub AS( SELECT a.empId, a.molId, b.rolId, d.molsDes, a.optId, c.optDes, c.optLink , a.`molsId` FROM segu_emp_mol_submol_opt a JOIN segu_emp_mol_rol b ON a.empId = b.empId AND a.molId = b.molId JOIN segu_opciones c ON a.optId = c.optId JOIN segu_sub_modulo d ON a.molsId = d.molsId );
CREATE OR REPLACE VIEW productos( id, cod_pareo, descripcion, observaciones, cod_rapido, cod_barra, tipo, codgrupo, grupo , codsubgrupo, sub_grupo , codcolor, color , moneda ,costo, neto, bruto, codmedida, medida , peso, alto , ancho , largo , volumen, minimo, inventariable, id_ext , url , codtalla , talla ,  created_at, updated_at) As ( SELECT a.prdId, prdCod, prdDes, prdObs, prdRap, prdEan, prdTip, c.grpCod ,c.grpDes , d.grpsCod, d.grpsDes , e.`colCod` , e.colDes , b.monCod , prdCost, prdNet, prdBrut, f.unCod,  f.unDes ,a.prdPes, a.prdAlto , a.`prdAncho` , a.`prdLargo` , a.`prdVolumen`,  prdMin,prdInv , `prdIdExt` , `prdUrl` , g.`tallaCod` , g.`tallaDes`  , a.created_at, a.updated_at from parm_producto a join parm_moneda b on a.monId = b.monId join parm_grupo c on a.grpId = c.grpId join parm_sub_grupo d on a.grpsId = d.grpsId join parm_color e on a.colId = e.colId join parm_un_medida f on a.unId = f.unId  join parm_talla g on a.tallaId  = g.tallaId );

CREATE OR REPLACE VIEW orden_produccion AS
    (SELECT 
        a.`empId`,
        `a`.`orpId` AS `id`,
        `a`.`orpUsrG` AS `usuario`,
        `a`.`orpNumOc` AS `orden_compra`,
        `a`.`orpNumRea` AS `orden_produccion`,
        b.`prvNom` AS proveedor,
        b.`prvTel` AS prv_telefono,
        b.prvId AS proveedor_id,
        `b`.`prvRut` AS `rut`,
        `a`.`orpFech` AS `fecha`,
        CASE
            WHEN `a`.`orpEst` = 1 THEN 'PENDIENTE'
            WHEN `a`.`orpEst` = 2 THEN 'PROCESANDO'
            WHEN `a`.`orpEst` = 3 THEN 'APROBADA'
            WHEN `a`.`orpEst` = 4 THEN 'RECHAZADA'
        END AS `estado_ord`,
        CASE
            WHEN `a`.`orpEstPrc` = 1 THEN 'PENDIENTE'
            WHEN `a`.`orpEstPrc` = 2 THEN 'PARCIAL'
            WHEN `a`.`orpEst` = 3 THEN 'APROBADA'
            WHEN `a`.`orpEst` = 4 THEN 'RECHAZADA'
        END AS `estado_pro`,
        `a`.`orpObs` AS `observaciones`,
        (SELECT 
                COUNT(0)
            FROM
                `prod_orden_det` `c`
            WHERE
                `c`.`orpId` = `a`.`orpId`) AS `prd_total`,
        f.clasTip AS tipo,
        f.clasTipDes AS tipo_des,
        f.clasTipId AS tipo_id,
        d.almId AS almacen_id,
        d.almDes AS almacen_destino,
        e.centroId AS centro_id,       
        e.cenDes AS centro_destino,
        a.orpHdrCustShortText5 as 'latitud',
        a.orpHdrCustShortText6 as 'longitud',
        a.orpHdrCustShortText9 as 'fech_promesa',        
        `a`.`created_at` AS `created_at`,
        `a`.`updated_at` AS `updated_at`
    FROM
        `prod_orden` `a`
            JOIN
        `parm_proveedor` `b` ON `a`.`prvId` = `b`.`prvId`
            JOIN
        sd_tip_clase f ON a.orpHdrCustShortText3 = f.clasTipId
            JOIN
        sd_centro_alm `d` ON a.orpHdrCustShortText1 = d.centroId
            AND a.orpHdrCustShortText2 = d.almId
            JOIN 
		sd_centro e on a.orpHdrCustShortText1 = e.centroId
        );