<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Cross-Origin Resource Sharing (CORS) Configuration
    |--------------------------------------------------------------------------
    |
    | Here you may configure your settings for cross-origin resource sharing
    | or "CORS". This determines what cross-origin operations may execute
    | in web browsers. You are free to adjust these settings as needed.
    |
    | To learn more: https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS
    |
    */

    'paths' => [
        'api/*',
        'sanctum/csrf-cookie',
        'productos',
        'log',
        'updRoles',
        'insRoles',
        'delRoles',
        'insEtapas',
        'delEtapas',
        'udpEtapas',
        'insEtapasDet',
        'delEtapasDet',
        'updEtapasDet',
        'insUser',
        'up_Password',
        'insGerencia',
        'updGerencia',
        'delGerencia',
        'setUserSession',
        'valUsuario',
        'upUsuario',
        'upUsuario2',
        'updEtapas',
        'insPais',
        'delPais',
        'updPais',
        'insRegion',
        'delRegion',
        'updRegion',
        'insComuna',
        'delComuna',
        'updComuna',
        'insCiudad',
        'delCiudad',
        'updCiudad',
        'insProveedor',
        'insPrvDes',
        'updProveedor',
        'delPrvDir',
        'insMoneda',
        'updMoneda',
        'delMoneda',
        'insColor',
        'updColor',
        'delColor',
        'insUnidad',
        'updUnidad',
        'delUnidad',
        'insGrupo',
        'updGrupo',
        'delGrupo',
        'insSubGrupo',
        'updSubGrupo',
        'delSubGrupo',
        'insProducto',
        'updProducto',
        'insOrd',
        'insOT',
        'insMaquinas',
        'updMaquinas',
        'delMaquinas',
        'insCalJul',
        'updCalJul',
        'delCalJul',
        'insLogSys',
        'insMezcla',
        'confMezcla',
        'rechaMezcla',
        'insExtrusion',
        'insConfirma',
        'confExtru',
        'insConfirmaO',
        'insConfirmaC',
        'insMotivo',
        'updMotivo',
        'delMotivo',
        'rechaExtru',
        'insRolMod',
        'confExtruO',
        'insTerm',
        'insTermCierre',
        'insTermCierreC',
        'uploadArTer',
        'delTermArcv',
        'insEquival',
        'valEqui',
        'insTermDet',
        'delTermDes',
        'termPallet',
        'termRechazo',
        'termConf',
        'insEnv',
        'upEnv',
        'insEnvDet',
        'envConf',
        'envRechazo',
        'upEnvC',
        'uploadArEnv',
        'delEnvArcv',
        'upBins',
        'insIny',
        'insInyCierre',
        'uploadArIny',
        'delInyArcv',
        'insInyCierreC',
        'inyConf',
        'inyRechazo',
        'insImp',
        'insImpCierre',
        'insImpCierreC',
        'impConf',
        'impRechazo',
        'insOTT',
        'lecturaNot',
        'lecturaNotAll',
        'AprOt',
        'insModulo',
        'insRolMod',
        'insRolOpt',
        'insMol',
        'updTipPag',
        'insTipPag',
        'delTipPag',
        'insOrdV',
        'transbank',
        'transbankRe',
        'insModulo',
        'upModulo',
        'delModulo',
        'insEmpresa',
        'insOpciones',
        'updOpciones',
        'delOpciones',
        'insAcciones',
        'updAcciones',
        'delAcciones',
        'insEmpOpt',
        'insUserAdm',
        'reiniciar',
        'deshabilitar',
        'habilitar',
        'reiniciarAdm',
        'deshabilitarAdm',
        'habilitarAdm',
        'insSubOpc',
        'delSubOpc',
        'weebhooks_oms_wooecommerce',
        'updEmpresa',
        'insCentro',
        'delCentro',
        'updCentro',
        'insAlmacen',
        'delAlmacen',
        'updAlmacen',
        'insSdOrden',
        'insSdClass',
        'updSdClass',
        'insSector',
        'delSector',
        'updSector',
        'insSdStock',
        'insOrdProduccion',
        'insOrdTrasInt',
        'ordenChEstA',
        'logPda',
        'insTalla',
        'updTalla',
        'delTalla',
        'cambiarPassword',
        'cargaMasivaReg',
        'updOrdProduccion',
        'pdfOrdenes',
        'pdfOrdenStatus',
        'liberarOrdenes',
        'estadoOrden',
        'cerrarRecepcion',
        'updateConfigField',
    ],

    'allowed_methods' => ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS'],

    'allowed_origins' => ['*'],

    'allowed_origins_patterns' => [],

    'allowed_headers' => [
        'Content-Type',
        'Authorization',
        'X-Requested-With',
        'X-CSRF-TOKEN',
        'X-XSRF-TOKEN',
        'x-xsrf-token',
        'Accept',
        'Origin',
        'X-API-Key',
        'X-App-Version',
        'X-Platform',
        'Cache-Control',
        'X-File-Name',
        'Pragma',
        'Expires',
        'If-Modified-Since',
        'If-None-Match',
        'ETag',
        'Last-Modified',
        'access-token',
        'X-Test-Header',
        'X-Custom-Header',
    ],

    'exposed_headers' => [
        'Cache-Control',
        'Content-Language',
        'Content-Type',
        'Expires',
        'Last-Modified',
        'Pragma',
        'ETag',
    ],

    'max_age' => 86400, // 24 horas

    'supports_credentials' => true,

]; 