name: Deploy Laravel PRD

on:
  push:
    branches:
      - main # Asegúrate de que tu rama se llame 'main' (o cámbialo a 'master')

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Descargar el código del repositorio
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Autenticación con Google Cloud usando tu Secreto JSON
      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # 3. Configurar Docker con el Helper de la región us-west1 (Oregón)
      # Esto arregla el error de "Unauthenticated request"
      - name: Setup Docker Helper
        run: |
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      # 4. Construir y Subir la imagen al repositorio existente
      - name: Build and Push Image
        run: |
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest .
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest

      # 5. Desplegar en Cloud Run inyectando el .env desde Secret Manager
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: back-agileti
          region: us-west1
          image: us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest
          # Montamos el secreto 'Laravel-env' como el archivo .env real dentro del contenedor
          flags: "--update-secrets=/var/www/html/.env=Laravel-env:latest"
