name: Deploy Laravel PRD
on:
  push:
    branches:
      - main # Cambia esto si tu rama principal se llama 'master'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # 1. Autenticación con Google Cloud
      - name: Google Auth
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # 2. Configurar Docker para Google Cloud
      - name: Setup Docker
        run: gcloud auth configure-docker --quiet

      # 3. Construir y subir la imagen al repositorio en us-west1 (Oregón)
      - name: Build and Push Image
        run: |
          # La URL ahora empieza con us-west1-docker.pkg.dev
          docker build -t us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest .
          docker push us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest

      # 4. Desplegar en Cloud Run usando la imagen de Oregón
      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: back-agileti
          region: us-west1 # Desplegamos también en Oregón para evitar latencia
          image: us-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/cloud-run-source-deploy/laravel-app:latest
          flags: "--update-secrets=/var/www/html/.env=Laravel-env:latest"
